import type { RecentParticipant } from "./types";

export const MOCK_RECENT_PARTICIPANTS: RecentParticipant[] = [
  {
    id: "op-01",
    name: "Aanya Sharma",
    company: "Google",
    signature: "Innovation Catalyst",
    gift: "Eco Felt Business Tote",
    leadScore: 88,
    conversationStatus: "complete",
    completedAt: "16:42",
  },
  {
    id: "op-02",
    name: "Rohan Mehta",
    company: "IBM",
    signature: "Execution Expert",
    gift: "Brushed Steel Desk Bottle",
    leadScore: 84,
    conversationStatus: "in_progress",
    completedAt: "16:31",
  },
  {
    id: "op-03",
    name: "Priya Reddy",
    company: "Microsoft",
    signature: "Culture Builder",
    gift: "Magnus Executive Notebook",
    leadScore: 81,
    conversationStatus: "pending",
    completedAt: "16:18",
  },
  {
    id: "op-04",
    name: "Arjun Patel",
    company: "Infosys",
    signature: "Strategic Planner",
    gift: "Minimal Desk Accent Set",
    leadScore: 79,
    conversationStatus: "complete",
    completedAt: "16:05",
  },
  {
    id: "op-05",
    name: "Meera Iyer",
    company: "Salesforce",
    signature: "Experience Curator",
    gift: "Eco Felt Business Tote",
    leadScore: 86,
    conversationStatus: "pending",
    completedAt: "15:52",
  },
  {
    id: "op-06",
    name: "Kabir Nair",
    company: "Qualcomm",
    signature: "Growth Enabler",
    gift: "Enamel Leadership Pin",
    leadScore: 72,
    conversationStatus: "complete",
    completedAt: "15:40",
  },
  {
    id: "op-07",
    name: "Anika Das",
    company: "ServiceNow",
    signature: "People Connector",
    gift: "Magnus Executive Notebook",
    leadScore: 77,
    conversationStatus: "in_progress",
    completedAt: "15:28",
  },
  {
    id: "op-08",
    name: "Dev Kapoor",
    company: "Micron",
    signature: "Sustainable Strategist",
    gift: "Premium Leather Card Sleeve",
    leadScore: 91,
    conversationStatus: "complete",
    completedAt: "15:11",
  },
  {
    id: "op-09",
    name: "Sara Khan",
    company: "Apple",
    signature: "Innovation Catalyst",
    gift: "Brushed Steel Desk Bottle",
    leadScore: 83,
    conversationStatus: "pending",
    completedAt: "14:58",
  },
  {
    id: "op-10",
    name: "Vikram Rao",
    company: "Amgen",
    signature: "Culture Builder",
    gift: "Eco Felt Business Tote",
    leadScore: 75,
    conversationStatus: "complete",
    completedAt: "14:44",
  },
];
